### ISSUE TITLE
Github action?

### ISSUE THREAD

**Issue by gardar** [hoo29/little-timmy#19]
It would great if there was a ready made github action published which one could use to detect unused ansible variables in ansible collection/role repositories.

**Comment by hoo29** [comment]
Sure - I can have a look at that sometime next week.

**Comment by hoo29** [comment]
Added

```yaml
name: little-timmy
on:
  push:
jobs:
  little-timmy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run action
        uses: hoo29/little-timmy@v1.0.0
```

The available config is in the readme - let me know if it works for you!
